Repository xamarin/Xamarin.Forms, pull requests merged in 2018-09, with the labels that each got.

#3635 [iOS] Specify a default size for UISearchBar width if needed
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue3413.cs
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
  Xamarin.Forms.Platform.iOS/Renderers/SearchBarRenderer.cs
Labels: blocker

#3570 [UWP] Fixed double set margins in Layouts
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla41418.cs
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue3398.cs
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
  Xamarin.Forms.Platform.UAP/ScrollViewRenderer.cs
  Xamarin.Forms.Platform.UAP/ViewRenderer.cs
Labels: API-change, blocker

#3559 [Android] Support multiple clipping settings in single layout
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/MultipleClipToBounds.cs
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
  Xamarin.Forms.Platform.Android/VisualElementTracker.cs
Labels: p/Android, t/bug :bug:

#3723 [UWP] uncomment tests that are now passing for 3188
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2338.cs
Labels: p/UWP, t/housekeeping ♻︎

#3632 [UITest] Update Xamarin.UITest nuget package
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla26171.cs
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1733.cs
  Xamarin.Forms.Core.Android.UITests/Xamarin.Forms.Core.Android.UITests.csproj
  Xamarin.Forms.Core.Android.UITests/packages.config
  Xamarin.Forms.Core.UITests.Shared/Tests/Legacy-CellsUITests.cs
  Xamarin.Forms.Core.UITests.Shared/Tests/ToolbarItemTests.cs
  Xamarin.Forms.Core.Windows.UITests/Xamarin.Forms.Core.Windows.UITests.csproj
  Xamarin.Forms.Core.Windows.UITests/packages.config
  Xamarin.Forms.Core.iOS.UITests/Xamarin.Forms.Core.iOS.UITests.csproj
  Xamarin.Forms.Core.iOS.UITests/packages.config
  Xamarin.Forms.Core.macOS.UITests/Xamarin.Forms.Core.macOS.UITests.csproj
  Xamarin.Forms.Core.macOS.UITests/packages.config
Labels: approved, t/housekeeping ♻︎

#3746 [Android] Revert bad merge
  Xamarin.Forms.Platform.Android/AppCompat/Platform.cs
Labels: approved

#3698 [Android, iOS] Fixes layout compression causes
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue3624.cs
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
  Xamarin.Forms.Platform.Android/VisualElementPackager.cs
  Xamarin.Forms.Platform.Android/VisualElementRenderer.cs
  Xamarin.Forms.Platform.iOS/RendererPool.cs
Labels: approved

#3771 Fix tests
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla32898.cs
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2499.cs
  Xamarin.Forms.Platform.iOS/RendererPool.cs
Labels: approved, t/housekeeping ♻︎

#3751 [Android Maps] Make markers available to subclasses
  Xamarin.Forms.Maps.Android/MapRenderer.cs
Labels: a/maps :globe_with_meridians:, p/Android, t/enhancement ➕

#3791 [UITests] wait for element before querying for it
  Xamarin.Forms.Core.UITests.Shared/Utilities/AppExtensions.cs
  Xamarin.Forms.Core.UITests.Shared/Utilities/Gestures.cs
Labels: t/housekeeping ♻︎

#3752 WPF - Fix Local store not persistant when restarting App
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue3541.cs
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
  Xamarin.Forms.Platform.WPF/Deserializer.cs
Labels: p/WPF

#3792 [UWP] implement Replace without reloading ListView
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue3788.cs
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
  Xamarin.Forms.Platform.UAP/ListViewRenderer.cs
Labels: approved

#3819 [iOS] Use UIApperance default color for UISwitch
  Xamarin.Forms.ControlGallery.iOS/AppDelegate.cs
  Xamarin.Forms.Platform.iOS/Renderers/SwitchRenderer.cs
Labels: p/iOS 🍎

#3835 [UITests] replace awaits with more reliable WaitForElement
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1733.cs
Labels: t/housekeeping ♻︎

#3823 [Core] Propagate BindingContext changes to TitleView
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
  Xamarin.Forms.Core.UnitTests/TitleViewUnitTests.cs
  Xamarin.Forms.Core.UnitTests/Xamarin.Forms.Core.UnitTests.csproj
  Xamarin.Forms.Core/NavigationPage.cs
  Xamarin.Forms.Core/Page.cs
Labels: API-change, approved

#3786 [A] do not draw gradient for empty CornerRadius
  Xamarin.Forms.Platform.Android/Renderers/BoxRenderer.cs
Labels: approved

#3879 [Enhancement] Create a bindable property for AutomationId
  Xamarin.Forms.Core/Element.cs
Labels: API-change

#3899 [Android] Prevent double time/date picker dialogs on Android when setting focus
  Xamarin.Forms.Platform.Android/Renderers/DatePickerRenderer.cs
  Xamarin.Forms.Platform.Android/Renderers/TimePickerRenderer.cs
Labels: p/Android

#3762 WPF - Fix Unable to intercept back button
  Xamarin.Forms.Platform.WPF/Renderers/NavigationPageRenderer.cs
Labels: p/WPF

#3364 [Android] Make native Android Platforms accessible via Context
  Xamarin.Forms.Platform.Android/AppCompat/FormsAppCompatActivity.cs
  Xamarin.Forms.Platform.Android/AppCompat/NavigationPageRenderer.cs
  Xamarin.Forms.Platform.Android/AppCompat/Platform.cs
  Xamarin.Forms.Platform.Android/AppCompat/TabbedPageRenderer.cs
  Xamarin.Forms.Platform.Android/FormsApplicationActivity.cs
  Xamarin.Forms.Platform.Android/Platform.cs
  Xamarin.Forms.Platform.Android/Renderers/MasterDetailRenderer.cs
  Xamarin.Forms.Platform.Android/Renderers/NavigationRenderer.cs
Labels: p/Android

#3896 [UWP] fixes tabstops of TimePicker, DatePiker. SearchBar, Stepper
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue3872.cs
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
  Xamarin.Forms.Platform.UAP/DatePickerRenderer.cs
  Xamarin.Forms.Platform.UAP/ITabStopOnDescendants.cs
  Xamarin.Forms.Platform.UAP/SearchBarRenderer.cs
  Xamarin.Forms.Platform.UAP/StepperRenderer.cs
  Xamarin.Forms.Platform.UAP/TimePickerRenderer.cs
  Xamarin.Forms.Platform.UAP/VisualElementRenderer.cs
  Xamarin.Forms.Platform.UAP/Xamarin.Forms.Platform.UAP.csproj
Labels: API-change

#3141 [UWP] Allow setting StepFrequency of the Slider
  Xamarin.Forms.Platform.UAP/SliderRenderer.cs
Labels: API-change, breaking, t/enhancement ➕

#3907 WPF - Apply font fix for button and span
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2187.cs
  Xamarin.Forms.Platform.WPF/Extensions/FontExtensions.cs
Labels: p/WPF

#3928 Fix UI test 39378
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla39378.xaml
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla39378.xaml.cs
Labels: t/housekeeping ♻︎

#3909 [Android] Update ClipBounds when View bounds changes
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/ViewClipBoundsShouldUpdate.cs
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
  Xamarin.Forms.Platform.Android/VisualElementTracker.cs
Labels: t/bug :bug:

#3914 Automate UI test B45702
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla45702.cs
  Xamarin.Forms.Controls/App.cs
Labels: t/housekeeping ♻︎
