Repository xamarin/Xamarin.Forms, pull requests merged in 2018-02, with the labels that each got.

#1861 Add ProgressColor on ProgressBar
  Xamarin.Forms.Controls/CoreGalleryPages/ProgressBarCoreGalleryPage.cs
  Xamarin.Forms.Core.UnitTests/NotifiedPropertiesTests.cs
  Xamarin.Forms.Core/ProgressBar.cs
  Xamarin.Forms.CustomAttributes/TestAttributes.cs
  Xamarin.Forms.Platform.Android/Renderers/ProgressBarRenderer.cs
  Xamarin.Forms.Platform.MacOS/Renderers/ProgressBarRenderer.cs
  Xamarin.Forms.Platform.Tizen/Renderers/ProgressBarRenderer.cs
  Xamarin.Forms.Platform.UAP/ProgressBarRenderer.cs
  Xamarin.Forms.Platform.WPF/Renderers/ProgressBarRenderer.cs
  Xamarin.Forms.Platform.iOS/Renderers/ProgressBarRenderer.cs
  docs/Xamarin.Forms.Core/Xamarin.Forms/ProgressBar.xml
Labels: F100, community-sprint, t/enhancement

#1892 [UITest] Update packages
  Xamarin.Forms.ControlGallery.iOS/Xamarin.Forms.ControlGallery.iOS.csproj
  Xamarin.Forms.ControlGallery.iOS/packages.config
  Xamarin.Forms.Core.Android.UITests/Xamarin.Forms.Core.Android.UITests.csproj
  Xamarin.Forms.Core.Android.UITests/packages.config
  Xamarin.Forms.Core.Windows.UITests/Xamarin.Forms.Core.Windows.UITests.csproj
  Xamarin.Forms.Core.Windows.UITests/packages.config
  Xamarin.Forms.Core.iOS.UITests/Xamarin.Forms.Core.iOS.UITests.csproj
  Xamarin.Forms.Core.iOS.UITests/packages.config
  Xamarin.Forms.Core.macOS.UITests/Xamarin.Forms.Core.macOS.UITests.csproj
  Xamarin.Forms.Core.macOS.UITests/packages.config
Labels: DO-NOT-MERGE-!!!

#1784 [Android] PlatformSpecific for WebView mixed content
  Xamarin.Forms.Controls/CoreGalleryPages/WebViewCoreGalleryPage.cs
  Xamarin.Forms.Core.UnitTests/WebViewUnitTests.cs
  Xamarin.Forms.Core/PlatformConfiguration/AndroidSpecific/WebView.cs
  Xamarin.Forms.CustomAttributes/TestAttributes.cs
  Xamarin.Forms.Platform.Android/Renderers/WebViewRenderer.cs
  docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration.AndroidSpecific/MixedContentHandling.xml
  docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration.AndroidSpecific/WebView.xml
  docs/Xamarin.Forms.Core/index.xml
Labels: F100, community-sprint, p/Android, t/enhancement

#1829 [Android,Core] Entry platform specific to set ImeOptions and flags
  Xamarin.Forms.Controls/GalleryPages/PlatformSpecificsGalleries/EntryPageAndroid.cs
  Xamarin.Forms.Controls/GalleryPages/PlatformSpecificsGallery.cs
  Xamarin.Forms.Core/PlatformConfiguration/AndroidSpecific/Entry.cs
  Xamarin.Forms.Platform.Android/Extensions/EntryRendererExtensions.cs
  Xamarin.Forms.Platform.Android/Renderers/EntryRenderer.cs
  Xamarin.Forms.Platform.Android/Xamarin.Forms.Platform.Android.csproj
  docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration.AndroidSpecific/Entry.xml
  docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration.AndroidSpecific/ImeFlags.xml
  docs/Xamarin.Forms.Core/index.xml
Labels: F100, community-sprint, t/enhancement

#1836 [All] IsSpellCheckEnabled on Entry/Editor
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1660.cs
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
  Xamarin.Forms.Core/InputView.cs
  Xamarin.Forms.Platform.Android/Renderers/EditorRenderer.cs
  Xamarin.Forms.Platform.Android/Renderers/EntryRenderer.cs
  Xamarin.Forms.Platform.UAP/EditorRenderer.cs
  Xamarin.Forms.Platform.UAP/EntryRenderer.cs
  Xamarin.Forms.Platform.UAP/FormsTextBoxStyle.xaml
  Xamarin.Forms.Platform.iOS/Renderers/EditorRenderer.cs
  Xamarin.Forms.Platform.iOS/Renderers/EntryRenderer.cs
  docs/Xamarin.Forms.Core/Xamarin.Forms/InputView.xml
Labels: F100, t/enhancement

#1824 [UWP] Add SearchBar platform specific for IsSpellCheckEnabled.
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1691_2.cs
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
  Xamarin.Forms.Core/PlatformConfiguration/WindowsSpecific/SearchBar.cs
  Xamarin.Forms.Platform.UAP/AutoSuggestStyle.xaml
  Xamarin.Forms.Platform.UAP/SearchBarRenderer.cs
  docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration.WindowsSpecific/SearchBar.xml
  docs/Xamarin.Forms.Core/index.xml
Labels: F100, community-sprint, p/UWP, t/enhancement

#1873 [Android] Allow customizing Android MenuItem
  Xamarin.Forms.Platform.Android/AppCompat/NavigationPageRenderer.cs
Labels: t/enhancement

#1880 Implemented MaxLength property on Entry and Editor
  Xamarin.Forms.Controls/CoreGalleryPages/EditorCoreGalleryPage.cs
  Xamarin.Forms.Controls/CoreGalleryPages/EntryCoreGalleryPage.cs
  Xamarin.Forms.Core/InputView.cs
  Xamarin.Forms.CustomAttributes/TestAttributes.cs
  Xamarin.Forms.Platform.Android/Renderers/EditorRenderer.cs
  Xamarin.Forms.Platform.Android/Renderers/EntryRenderer.cs
  Xamarin.Forms.Platform.GTK/Controls/EntryWrapper.cs
  Xamarin.Forms.Platform.GTK/Controls/ScrolledTextView.cs
  Xamarin.Forms.Platform.GTK/Renderers/EditorRenderer.cs
  Xamarin.Forms.Platform.GTK/Renderers/EntryRenderer.cs
  Xamarin.Forms.Platform.MacOS/Renderers/EditorRenderer.cs
  Xamarin.Forms.Platform.MacOS/Renderers/EntryRenderer.cs
  Xamarin.Forms.Platform.Tizen/Renderers/EditorRenderer.cs
  Xamarin.Forms.Platform.Tizen/Renderers/EntryRenderer.cs
  Xamarin.Forms.Platform.UAP/EditorRenderer.cs
  Xamarin.Forms.Platform.UAP/EntryRenderer.cs
  Xamarin.Forms.Platform.WPF/Renderers/EditorRenderer.cs
  Xamarin.Forms.Platform.WPF/Renderers/EntryRenderer.cs
  Xamarin.Forms.Platform.iOS/Renderers/EditorRenderer.cs
  Xamarin.Forms.Platform.iOS/Renderers/EntryRenderer.cs
  docs/Xamarin.Forms.Core/Xamarin.Forms/InputView.xml
Labels: F100, community-sprint, t/enhancement

#1854 [iOS] ListView full width separators
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1665.cs
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
  Xamarin.Forms.Core/PlatformConfiguration/iOSSpecific/ListView.cs
  Xamarin.Forms.Core/PlatformConfiguration/iOSSpecific/SeparatorStyle.cs
  Xamarin.Forms.Platform.iOS/Renderers/ListViewRenderer.cs
  docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration.iOSSpecific/ListView.xml
  docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration.iOSSpecific/SeparatorStyle.xml
  docs/Xamarin.Forms.Core/index.xml
Labels: F100, community-sprint, t/enhancement

#1896 [iOS] Add shadow effect
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1707.cs
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
  Xamarin.Forms.Core/PlatformConfiguration/iOSSpecific/VisualElement.cs
  Xamarin.Forms.Platform.iOS/Properties/AssemblyInfo.cs
  Xamarin.Forms.Platform.iOS/ShadowEffect.cs
  Xamarin.Forms.Platform.iOS/Xamarin.Forms.Platform.iOS.csproj
  docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration.iOSSpecific/VisualElement+ShadowEffect.xml
  docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration.iOSSpecific/VisualElement.xml
  docs/Xamarin.Forms.Core/index.xml
Labels: F100, t/enhancement

#1833 AutoCapitalization support for Entry/Editor
  Xamarin.Forms.ControlGallery.Android/CustomRenderers.cs
  Xamarin.Forms.ControlGallery.WindowsUniversal/CustomRenderers.cs
  Xamarin.Forms.ControlGallery.iOS/CustomRenderers.cs
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1683.cs
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
  Xamarin.Forms.Core/KeyboardFlags.cs
  Xamarin.Forms.Platform.Android/Renderers/KeyboardExtensions.cs
  Xamarin.Forms.Platform.UAP/KeyboardExtensions.cs
  Xamarin.Forms.Platform.iOS/Extensions/Extensions.cs
  docs/Xamarin.Forms.Core/Xamarin.Forms/KeyboardFlags.xml
Labels: F100, t/enhancement

#1870 Allow users to specify resolution method for handlers, effects, and services
  Xamarin.Forms.Core.UnitTests/DependencyResolutionTests.cs
  Xamarin.Forms.Core.UnitTests/Xamarin.Forms.Core.UnitTests.csproj
  Xamarin.Forms.Core/DependencyResolver.cs
  Xamarin.Forms.Core/DependencyService.cs
  Xamarin.Forms.Core/Effect.cs
  Xamarin.Forms.Core/Registrar.cs
  docs/Xamarin.Forms.Core/Xamarin.Forms.Internals/DependencyResolver.xml
  docs/Xamarin.Forms.Core/Xamarin.Forms/DependencyService.xml
  docs/Xamarin.Forms.Core/index.xml
Labels: F100, t/enhancement

#1910 [Core, iOS, Android, UWP, WPF] Hide scroll view scroll bars
  Xamarin.Forms.Controls/GalleryPages/ScrollGallery.cs
  Xamarin.Forms.Core/ScrollBarVisibility.cs
  Xamarin.Forms.Core/ScrollView.cs
  Xamarin.Forms.Platform.Android/Renderers/ScrollViewRenderer.cs
  Xamarin.Forms.Platform.GTK/Renderers/ScrollViewRenderer.cs
  Xamarin.Forms.Platform.MacOS/Renderers/ScrollViewRenderer.cs
  Xamarin.Forms.Platform.Tizen/Renderers/ScrollViewRenderer.cs
  Xamarin.Forms.Platform.UAP/ScrollViewRenderer.cs
  Xamarin.Forms.Platform.WPF/Renderers/EditorRenderer.cs
  Xamarin.Forms.Platform.WPF/Renderers/ScrollViewRenderer.cs
  Xamarin.Forms.Platform.iOS/Renderers/ScrollViewRenderer.cs
  docs/Xamarin.Forms.Core/Xamarin.Forms/ScrollBarVisibility.xml
  docs/Xamarin.Forms.Core/Xamarin.Forms/ScrollView.xml
  docs/Xamarin.Forms.Core/index.xml
Labels: F100, community-sprint, t/enhancement
