Repository xamarin/Xamarin.Forms, pull requests merged in 2018-05, with the labels that each got.

#2392 [UWP] Fix crash when closing app and not actually loading an Application
  Xamarin.Forms.Platform.UAP/WindowsBasePage.cs
Labels: i/critical, p/UWP

#2582 [XamlG] creates fields for x:Name on root
  Xamarin.Forms.Build.Tasks/SetFieldVisitor.cs
  Xamarin.Forms.Build.Tasks/XamlGenerator.cs
  Xamarin.Forms.Xaml.UnitTests/Issues/Gh2574.xaml
  Xamarin.Forms.Xaml.UnitTests/Issues/Gh2574.xaml.cs
  Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
  Xamarin.Forms.Xaml.UnitTests/XamlgTests.cs
Labels: a/Xaml, t/bug :bug:

#2476 Adding support for tapping on iOS Slider to set value
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1729.cs
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
  Xamarin.Forms.Core/PlatformConfiguration/iOSSpecific/Slider.cs
  Xamarin.Forms.Platform.iOS/Renderers/SliderRenderer.cs
Labels: API-change, F100, community-sprint, t/enhancement

#2506 [UWP] Activating vertical scrolling in the Alert dialog box.
  Xamarin.Forms.Platform.UAP/AlertDialog.cs
  Xamarin.Forms.Platform.UAP/PlatformUWP.cs
  Xamarin.Forms.Platform.UAP/Xamarin.Forms.Platform.UAP.csproj
Labels: API-change, breaking, p/UWP

#2515 [UWP] Added margin inside scroll view
  Xamarin.Forms.Platform.UAP/ScrollViewRenderer.cs
  Xamarin.Forms.Platform.UAP/ViewRenderer.cs
Labels: p/UWP

#2556 Namescope enhancements
  Xamarin.Forms.Build.Tasks/NodeILExtensions.cs
  Xamarin.Forms.Build.Tasks/SetNamescopesAndRegisterNamesVisitor.cs
  Xamarin.Forms.Core/ConstraintExpression.cs
  Xamarin.Forms.Core/Element.cs
  Xamarin.Forms.Core/Internals/INameScope.cs
  Xamarin.Forms.Core/Internals/INamescopeProvider.cs
  Xamarin.Forms.Core/Internals/NameScope.cs
  Xamarin.Forms.Core/NameScopeExtensions.cs
  Xamarin.Forms.Core/ReferenceTypeConverter.cs
  Xamarin.Forms.Core/Xaml/IReferenceProvider.cs
  Xamarin.Forms.Xaml.UnitTests/DynamicResource.xaml.cs
  Xamarin.Forms.Xaml.UnitTests/Issues/Gh2517.xaml.cs
  Xamarin.Forms.Xaml.UnitTests/NameScopeTests.cs
  Xamarin.Forms.Xaml/CreateValuesVisitor.cs
  Xamarin.Forms.Xaml/MarkupExtensions/ReferenceExtension.cs
  Xamarin.Forms.Xaml/NamescopingVisitor.cs
  Xamarin.Forms.Xaml/Properties/AssemblyInfo.cs
  Xamarin.Forms.Xaml/XamlServiceProvider.cs
Labels: API-change, a/Xaml, t/enhancement

#2569 [C][flex] proper handling of grow in reverse
  Xamarin.Flex/Flex.cs
  Xamarin.Forms.Core.UnitTests/FlexLayoutTests.cs
Labels: a/flex, a/layout, t/bug :bug:

#2292 [UWP] TableView should not crash when Control is null OnSelectionChanged
  Xamarin.Forms.Platform.UAP/TableViewRenderer.cs
Labels: i/critical, p/UWP, t/bug :bug:

#2599 [CSS] lightgray is spelled lightgrey in CSS world
  Xamarin.Forms.Build.Tasks/CompiledConverters/ColorTypeConverter.cs
  Xamarin.Forms.Core/ColorTypeConverter.cs
Labels: a/CSS, t/bug :bug:

#2594 [Flex] do not layout invisible children
  Xamarin.Flex/Flex.cs
  Xamarin.Forms.Core.UnitTests/FlexLayoutTests.cs
  Xamarin.Forms.Core/FlexLayout.cs
Labels: a/flex, a/layout, t/bug :bug:

#2215 [Android] Second measurement pass in IPlatform.GetNativeSize
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1396.cs
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1415.cs
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
  Xamarin.Forms.Core/Device.cs
  Xamarin.Forms.Core/Layout.cs
  Xamarin.Forms.Platform.Android/AppCompat/Platform.cs
  Xamarin.Forms.Platform.Android/FastRenderers/ButtonRenderer.cs
  Xamarin.Forms.Platform.Android/FastRenderers/FrameRenderer.cs
  Xamarin.Forms.Platform.Android/FastRenderers/ImageRenderer.cs
  Xamarin.Forms.Platform.Android/FastRenderers/LabelRenderer.cs
  Xamarin.Forms.Platform.Android/Platform.cs
  Xamarin.Forms.Platform.Android/ViewRenderer.cs
Labels: a/layout, t/bug :bug:

#2132 Adding line height to Label and Span
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1734.cs
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
  Xamarin.Forms.Core/ILineHeightElement.cs
  Xamarin.Forms.Core/Label.cs
  Xamarin.Forms.Core/LineHeightElement.cs
  Xamarin.Forms.Core/Properties/AssemblyInfo.cs
  Xamarin.Forms.Core/Span.cs
  Xamarin.Forms.Platform.Android/FastRenderers/LabelRenderer.cs
  Xamarin.Forms.Platform.Android/Renderers/FormattedStringExtensions.cs
  Xamarin.Forms.Platform.Android/Renderers/LabelRenderer.cs
  Xamarin.Forms.Platform.UAP/LabelRenderer.cs
  Xamarin.Forms.Platform.iOS/Renderers/FormattedStringExtensions.cs
  Xamarin.Forms.Platform.iOS/Renderers/LabelRenderer.cs
Labels: API-change, F100, t/enhancement

#2012 [Core,iOS,Android] Placeholder and PlaceholderColor on Editor
  Xamarin.Forms.Controls/CoreGalleryPages/EditorCoreGalleryPage.cs
  Xamarin.Forms.Core/Editor.cs
  Xamarin.Forms.CustomAttributes/TestAttributes.cs
  Xamarin.Forms.Platform.Android/Renderers/EditorRenderer.cs
  Xamarin.Forms.Platform.UAP/EditorRenderer.cs
  Xamarin.Forms.Platform.iOS/Renderers/EditorRenderer.cs
Labels: API-change, t/enhancement

#1998 [Enhancement] Rounded corners on BoxView
  Xamarin.Forms.Controls/CoreGalleryPages/CoreBoxViewGalleryPage.cs
  Xamarin.Forms.Core/BoxView.cs
  Xamarin.Forms.Core/CornerRadius.cs
  Xamarin.Forms.Core/CornerRadiusTypeConverter.cs
  Xamarin.Forms.CustomAttributes/TestAttributes.cs
  Xamarin.Forms.Platform.Android/Renderers/BoxRenderer.cs
  Xamarin.Forms.Platform.GTK/Controls/BoxView.cs
  Xamarin.Forms.Platform.GTK/Renderers/BoxViewRenderer.cs
  Xamarin.Forms.Platform.MacOS/Controls/FormsBoxView.cs
  Xamarin.Forms.Platform.MacOS/Renderers/BoxViewRenderer.cs
  Xamarin.Forms.Platform.MacOS/Xamarin.Forms.Platform.macOS.csproj
  Xamarin.Forms.Platform.UAP/BoxViewRenderer.cs
  Xamarin.Forms.Platform.UAP/FormsButton.cs
  Xamarin.Forms.Platform.UAP/FrameRenderer.cs
  Xamarin.Forms.Platform.WPF/Renderers/BoxViewRenderer.cs
  Xamarin.Forms.Platform.WPF/Renderers/FrameRenderer.cs
  Xamarin.Forms.Platform.iOS/Renderers/BoxRenderer.cs
Labels: API-change, F100, community-sprint, t/enhancement

#2526 [UWP] Fix crashes animation in the thread pool
  Xamarin.Forms.Platform.UAP/WindowsBasePlatformServices.cs
Labels: API-change

#2643 [A] apply global scale on BatchUpdate
  Xamarin.Forms.Platform.Android/VisualElementTracker.cs
Labels: a/layout, p/Android, t/bug :bug:

#2650 Fixed out-of-date version
  README.md
Labels: t/housekeeping

#2645 [nuspec] update description to add new plats
  .nuspec/Xamarin.Forms.nuspec
Labels: t/enhancement, t/housekeeping

#2646 [iOS] allow mailto: uri
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla60691.cs
  Xamarin.Forms.Platform.iOS/Forms.cs
Labels: p/iOS, t/bug :bug:

#2620 [UWP] NRE when checking IsInNativeLayout during OnScrollToRequested
  Xamarin.Forms.Platform.UAP/ScrollViewRenderer.cs
Labels: API-change

#2673 [Core] Fixes getting the accelerator keys, if the key is equal to the separator
  Xamarin.Forms.Core.UnitTests/MenuItemTests.cs
  Xamarin.Forms.Core/Accelerator.cs
Labels: p/macOS, t/bug :bug:

#2426 [iOS, Android, UWP] Added padding to Button control
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/GitHub1702.cs
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
  Xamarin.Forms.Controls/CoreGalleryPages/ButtonCoreGalleryPage.cs
  Xamarin.Forms.Core/Button.cs
  Xamarin.Forms.CustomAttributes/TestAttributes.cs
  Xamarin.Forms.Platform.Android/AppCompat/ButtonRenderer.cs
  Xamarin.Forms.Platform.Android/FastRenderers/ButtonRenderer.cs
  Xamarin.Forms.Platform.Android/Renderers/ButtonRenderer.cs
  Xamarin.Forms.Platform.UAP/ButtonRenderer.cs
  Xamarin.Forms.Platform.iOS/Renderers/ButtonRenderer.cs
Labels: API-change, F100, community-sprint, t/enhancement

#2684 [Android] Fix issue #2634. Draw no border if no BorderColor is set
  Xamarin.Forms.Platform.Android/FastRenderers/FrameRenderer.cs
Labels: a/layout, i/regression, p/Android, t/bug :bug:

#2649 Call ChangeVisualState when new states are added
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2625.xaml
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2625.xaml.cs
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
  Xamarin.Forms.Core.UnitTests/VisualStateManagerTests.cs
  Xamarin.Forms.Core/VisualStateManager.cs
  Xamarin.Forms.Xaml.UnitTests/VisualStateManagerTests.xaml
  Xamarin.Forms.Xaml.UnitTests/VisualStateManagerTests.xaml.cs
Labels: API-change, a/VSM, t/bug :bug:

#2685 [Maps] Handle Pin.PropertyChanged events
  Xamarin.Forms.Controls/GalleryPages/MapGallery.cs
  Xamarin.Forms.Maps.Android/MapRenderer.cs
  Xamarin.Forms.Maps.iOS/MapRenderer.cs
Labels: a/maps :globe_with_meridians:, p/Android, p/iOS

#2682 [Android Maps] Fix pins not being removed
  Xamarin.Forms.Controls/GalleryPages/MapGallery.cs
  Xamarin.Forms.Maps.Android/MapRenderer.cs
Labels: a/maps :globe_with_meridians:, p/Android, t/bug :bug:

#2717 [UWP] fix NRE in SearchBarRenderer
  Xamarin.Forms.Platform.UAP/SearchBarRenderer.cs
Labels: 3.0.0, i/regression, p/UWP

#2749 [Android] Fixes TimePicker FontSize & FontFamily
  Xamarin.Forms.Platform.Android/Renderers/TimePickerRenderer.cs
Labels: p/Android, t/bug :bug:

#2791 [Core] Remove Guid.NewGuid() calls from performance tracking
  Xamarin.Forms.Core/Performance.cs
  Xamarin.Forms.Platform.Android/AppCompat/Platform.cs
  Xamarin.Forms.Platform.Android/Cells/CellRenderer.cs
  Xamarin.Forms.Platform.Android/Cells/ViewCellRenderer.cs
  Xamarin.Forms.Platform.Android/FastRenderers/ButtonRenderer.cs
  Xamarin.Forms.Platform.Android/FastRenderers/ImageRenderer.cs
  Xamarin.Forms.Platform.Android/Platform.cs
  Xamarin.Forms.Platform.Android/Renderers/ListViewAdapter.cs
  Xamarin.Forms.Platform.Android/VisualElementPackager.cs
  Xamarin.Forms.Platform.Android/VisualElementRenderer.cs
  Xamarin.Forms.Platform.Android/VisualElementTracker.cs
  Xamarin.Forms.Platform.iOS/Cells/CellRenderer.cs
  Xamarin.Forms.Platform.iOS/Cells/ViewCellRenderer.cs
  Xamarin.Forms.Platform.iOS/Platform.cs
  Xamarin.Forms.Platform.iOS/Renderers/ListViewRenderer.cs
  Xamarin.Forms.Platform.iOS/VisualElementPackager.cs
  Xamarin.Forms.Platform.iOS/VisualElementRenderer.cs
  Xamarin.Forms.Platform.iOS/VisualElementTracker.cs
Labels: API-change

#2797 [Xaml] avoid AmbiguousMatchException
  Xamarin.Forms.Xaml/ApplyPropertiesVisitor.cs
Labels: a/Xaml </>, i/regression

#2785 Fix ControlsGallery SearchBar HeightRequest issue
  Xamarin.Forms.Controls/TestCases.cs
Labels: t/housekeeping

#2806 [Tizen] Add CornerRadius implementation on BoxView
  Xamarin.Forms.Platform.Tizen/Native/RoundRectangle.cs
  Xamarin.Forms.Platform.Tizen/Renderers/BoxViewRenderer.cs
Labels: p/Tizen

#2808 [Tizen] Support LineHeight on Label,Span
  Xamarin.Forms.Platform.Tizen/Native/Label.cs
  Xamarin.Forms.Platform.Tizen/Native/Span.cs
  Xamarin.Forms.Platform.Tizen/Renderers/LabelRenderer.cs
Labels: p/Tizen

#2807 [Tizen] Add PlaceHolder implementation on Editor
  Xamarin.Forms.Platform.Tizen/Renderers/EditorRenderer.cs
Labels: p/Tizen

#2766 [Binding] avoid AmbiguousME on redefined property
  Xamarin.Forms.Core/BindingExpression.cs
  Xamarin.Forms.Xaml.UnitTests/Issues/Gh2632.xaml
  Xamarin.Forms.Xaml.UnitTests/Issues/Gh2632.xaml.cs
  Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
Labels: a/binding ⛓, a/netstandard, i/regression

#2773 [UWP] moved UpdateLayout call in ListViewRenderer into BeginInvokeOnMainThread
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2681.cs
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
  Xamarin.Forms.Platform.UAP/ListViewRenderer.cs
Labels: p/UWP

#2762 fixes #2653 on uwp set the Z Index when children aren't added to the end of the stack
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2653.cs
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
  Xamarin.Forms.Platform.UAP/VisualElementPackager.cs
Labels: a/layout, i/regression, p/UWP

#2539 Controlling Caret position on iOS,Android,UWP and color on iOS
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1667.cs
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
  Xamarin.Forms.Core/Entry.cs
  Xamarin.Forms.Core/PlatformConfiguration/iOSSpecific/Entry.cs
  Xamarin.Forms.Platform.Android/Renderers/EntryRenderer.cs
  Xamarin.Forms.Platform.Android/Renderers/FormsEditText.cs
  Xamarin.Forms.Platform.UAP/EntryRenderer.cs
  Xamarin.Forms.Platform.iOS/Renderers/EntryRenderer.cs
Labels: API-change, F100, community-sprint, t/enhancement

#2804 delay setting of source to help verify ui test block
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1583_1.cs
Labels: p/iOS 🍎, t/housekeeping

#2512 [UWP] Fixed sync of ListView items with ListViewProxy
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla56771.cs
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1875.cs
  Xamarin.Forms.Platform.UAP/ListViewRenderer.cs
Labels: i/regression, p/UWP

#2727 SwipeGestureRecognizer
  Xamarin.Forms.ControlGallery.Android/Xamarin.Forms.ControlGallery.Android.csproj
  Xamarin.Forms.Controls/ControlGalleryPages/SwipeGestureGalleryPage.cs
  Xamarin.Forms.Controls/CoreGallery.cs
  Xamarin.Forms.Controls/Xamarin.Forms.Controls.csproj
  Xamarin.Forms.Core.UnitTests/SwipeGestureRecognizerTests.cs
  Xamarin.Forms.Core.UnitTests/Xamarin.Forms.Core.UnitTests.csproj
  Xamarin.Forms.Core/ISwipeGestureController.cs
  Xamarin.Forms.Core/SwipeDirection.cs
  Xamarin.Forms.Core/SwipeGestureRecognizer.cs
  Xamarin.Forms.Core/SwipedEventArgs.cs
  Xamarin.Forms.Maps.Android/Xamarin.Forms.Maps.Android.csproj
  Xamarin.Forms.Platform.Android.AppLinks/Xamarin.Forms.Platform.Android.AppLinks.csproj
  Xamarin.Forms.Platform.Android/GestureManager.cs
  Xamarin.Forms.Platform.Android/InnerGestureListener.cs
  Xamarin.Forms.Platform.Android/SwipeGestureHandler.cs
  Xamarin.Forms.Platform.Android/Xamarin.Forms.Platform.Android.csproj
  Xamarin.Forms.Platform.Tizen/GestureDetector.cs
  Xamarin.Forms.Platform.Tizen/SwipeGestureHandler.cs
  Xamarin.Forms.Platform.UAP/VisualElementTracker.cs
  Xamarin.Forms.Platform.iOS/EventTracker.cs
Labels: API-change

#2827 Support default value for value types in BindableProperty
  Xamarin.Forms.Core.UnitTests/BindablePropertyUnitTests.cs
  Xamarin.Forms.Core/BindableProperty.cs
Labels: t/enhancement
