Repository xamarin/Xamarin.Forms, pull requests merged in 2018-04, with the labels that each got.

#2206 [Tizen] Support the ListView.SelectionMode property
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1801.cs
  Xamarin.Forms.Platform.Tizen/Renderers/ListViewRenderer.cs
Labels: t/enhancement

#2224 [Design] Allow numeric values for FontSize
  Xamarin.Forms.Core.Design/AttributeTableBuilder.cs
  Xamarin.Forms.Core.Design/NonExclusiveEnumConverter.cs
  Xamarin.Forms.Core.Design/Xamarin.Forms.Core.Design.csproj
Labels: API-change

#2323 [iOS] Grouped ListView will no longer crash when its ItemSource is cleared
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla45125.cs
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/GroupListViewHeaderIndexOutOfRange.cs
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
  Xamarin.Forms.Platform.iOS/Renderers/ListViewRenderer.cs
Labels: i/critical, i/regression, p/iOS, t/bug

#2409 [UI Tests] Add missing preserve attributes
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla43161.cs
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla45284.xaml.cs
Labels: t/housekeeping

#2335 fixed WebView typo, replaced Label icons, added FlexLayout
  Xamarin.Forms.Core.Design/Xamarin.Forms.Core.Design.csproj
  Xamarin.Forms.Core.Design/toolbox/Xamarin.Forms.toolbox.xml
  Xamarin.Forms.Core.Design/toolbox/icons/mac/layout-FlexLayout-16.png
  Xamarin.Forms.Core.Design/toolbox/icons/mac/layout-FlexLayout-16@2x.png
  Xamarin.Forms.Core.Design/toolbox/icons/mac/layout-FlexLayout-16~dark.png
  Xamarin.Forms.Core.Design/toolbox/icons/mac/layout-FlexLayout-16~dark@2x.png
  Xamarin.Forms.Core.Design/toolbox/icons/mac/layout-FlexLayout-16~dark~sel.png
  Xamarin.Forms.Core.Design/toolbox/icons/mac/layout-FlexLayout-16~dark~sel@2x.png
  Xamarin.Forms.Core.Design/toolbox/icons/mac/layout-FlexLayout-16~sel.png
  Xamarin.Forms.Core.Design/toolbox/icons/mac/layout-FlexLayout-16~sel@2x.png
  Xamarin.Forms.Core.Design/toolbox/icons/mac/view-Label-16-1.png
  Xamarin.Forms.Core.Design/toolbox/icons/mac/view-Label-16-3.png
  Xamarin.Forms.Core.Design/toolbox/icons/mac/view-Label-16.png
  Xamarin.Forms.Core.Design/toolbox/icons/mac/view-Label-16@2x-1.png
  Xamarin.Forms.Core.Design/toolbox/icons/mac/view-Label-16@2x-2.png
  Xamarin.Forms.Core.Design/toolbox/icons/mac/view-Label-16@2x-3.png
  Xamarin.Forms.Core.Design/toolbox/icons/mac/view-Label-16@2x.png
  Xamarin.Forms.Core.Design/toolbox/icons/mac/view-Label-16~dark.png
  Xamarin.Forms.Core.Design/toolbox/icons/mac/view-Label-16~dark@2x.png
  Xamarin.Forms.Core.Design/toolbox/icons/mac/view-Label-16~dark~sel.png
  Xamarin.Forms.Core.Design/toolbox/icons/mac/view-Label-16~dark~sel@2x.png
  Xamarin.Forms.Core.Design/toolbox/icons/mac/view-Label-16~sel.png
  Xamarin.Forms.Core.Design/toolbox/icons/mac/view-Label-16~sel@2x.png
  Xamarin.Forms.Core.Design/toolbox/icons/win/layout-FlexLayout-16.png
Labels: t/housekeeping

#2025 [XamlC] cache ImportReference and ImportMethodReference as they're slow
  Xamarin.Forms.Build.Tasks/CompiledConverters/BindingTypeConverter.cs
  Xamarin.Forms.Build.Tasks/CompiledConverters/BoundsTypeConverter.cs
  Xamarin.Forms.Build.Tasks/CompiledConverters/ColorTypeConverter.cs
  Xamarin.Forms.Build.Tasks/CompiledConverters/ConstraintTypeConverter.cs
  Xamarin.Forms.Build.Tasks/CompiledConverters/LayoutOptionsConverter.cs
  Xamarin.Forms.Build.Tasks/CompiledConverters/ListStringTypeConverter.cs
  Xamarin.Forms.Build.Tasks/CompiledConverters/RDSourceTypeConverter.cs
  Xamarin.Forms.Build.Tasks/CompiledConverters/RectangleTypeConverter.cs
  Xamarin.Forms.Build.Tasks/CompiledConverters/ThicknessTypeConverter.cs
  Xamarin.Forms.Build.Tasks/CompiledConverters/TypeTypeConverter.cs
  Xamarin.Forms.Build.Tasks/CompiledConverters/UriTypeConverter.cs
  Xamarin.Forms.Build.Tasks/CompiledMarkupExtensions/TypeExtension.cs
  Xamarin.Forms.Build.Tasks/CompiledValueProviders/StyleSheetProvider.cs
  Xamarin.Forms.Build.Tasks/CreateObjectVisitor.cs
  Xamarin.Forms.Build.Tasks/ModuleDefinitionExtensions.cs
  Xamarin.Forms.Build.Tasks/NodeILExtensions.cs
  Xamarin.Forms.Build.Tasks/SetNamescopesAndRegisterNamesVisitor.cs
  Xamarin.Forms.Build.Tasks/SetPropertiesVisitor.cs
  Xamarin.Forms.Build.Tasks/TypeDefinitionExtensions.cs
  Xamarin.Forms.Build.Tasks/TypeReferenceExtensions.cs
  Xamarin.Forms.Build.Tasks/XamlCTask.cs
Labels: a/Xaml

#2230 [msbuild] setup inputs and outputs for XamlC target
  .nuspec/Xamarin.Forms.targets
Labels: t/housekeeping

#2431 [Designer] Do not prefix the toolbox images
  Xamarin.Forms.Core.Design/Xamarin.Forms.Core.Design.csproj
Labels: i/critical, t/housekeeping

#2197 [Core] Centralizing visual state change checks and providing a method to override if users want to add/control state changes themselves
  Xamarin.Forms.Core.UnitTests/VisualStateManagerTests.cs
  Xamarin.Forms.Core/VisualElement.cs
Labels: API-change, a/VSM

#2428 [UWP] Only display one alert at a time
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla43469.cs
  Xamarin.Forms.Platform.UAP/PlatformUWP.cs
Labels: i/critical, i/regression, p/UWP

#2211 [WPF] Entry Placeholder property
  Xamarin.Forms.Platform.WPF/FormsTextBox.cs
  Xamarin.Forms.Platform.WPF/Renderers/EntryRenderer.cs
  Xamarin.Forms.Platform.WPF/WPFResources.xaml
Labels: API-change, p/WPF

#2436 [UWP] Prevent crash/unexpected behavior with ListView ScrollTo
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla43313.cs
  Xamarin.Forms.Platform.UAP/ListViewRenderer.cs
Labels: i/critical, i/regression, p/UWP

#2453 [UWP] Only reset ListView DataContext on INotifyCollectionChanged Reset
  Xamarin.Forms.Platform.UAP/ListViewRenderer.cs
Labels: i/regression

#2493 design dlls for all plats
  .nuspec/Xamarin.Forms.nuspec
Labels: t/bug

#2488 Removed invalid test that is adding no value
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1762.cs
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Labels: t/housekeeping

#2494 [XamlC] accept lowercase colors
  Xamarin.Forms.Build.Tasks/CompiledConverters/ColorTypeConverter.cs
  Xamarin.Forms.Build.Tasks/ModuleDefinitionExtensions.cs
  Xamarin.Forms.Xaml.UnitTests/SetValue.xaml
Labels: a/Xaml, t/enhancement

#2477 [XamlG] depends on PrepareResourceNames
  .nuspec/Xamarin.Forms.targets
Labels: 3.0.0, i/critical, i/regression

#2501 [UI Tests] Fixing Issue2266 to conform to new test structure and automating test
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2266.cs
Labels: t/housekeeping

#2500 [UITests] Fix failing tests
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla51825.cs
  Xamarin.Forms.Controls/ControlGalleryPages/ToolbarItems.cs
  Xamarin.Forms.Core.UITests.Shared/Tests/ToolbarItemTests.cs
Labels: t/housekeeping

#2414 [Android] Disable long press detection so it doesn't prevent pans in TapAndPanGestureDetector
  Xamarin.Forms.Platform.Android/GestureManager.cs
Labels: 3.0.0, i/regression, p/Android

#2433 [iOS] Picker IsFocused not being set back to false if nothing in picker was selected
  Xamarin.Forms.ControlGallery.Android/FormsAppCompatActivity.cs
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2339.cs
  Xamarin.Forms.Platform.iOS/Renderers/PickerRenderer.cs
Labels: 3.0.0, i/regression, p/iOS

#2487 [Xaml[C]] consider subclass of RDs as RDs
  Xamarin.Forms.Build.Tasks/CreateObjectVisitor.cs
  Xamarin.Forms.Build.Tasks/ExpandMarkupsVisitor.cs
  Xamarin.Forms.Build.Tasks/SetFieldVisitor.cs
  Xamarin.Forms.Build.Tasks/SetNamescopesAndRegisterNamesVisitor.cs
  Xamarin.Forms.Build.Tasks/SetPropertiesVisitor.cs
  Xamarin.Forms.Build.Tasks/SetResourcesVisitor.cs
  Xamarin.Forms.Xaml.UnitTests/Issues/Gh2483.xaml
  Xamarin.Forms.Xaml.UnitTests/Issues/Gh2483.xaml.cs
  Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
  Xamarin.Forms.Xaml/ApplyPropertiesVisitor.cs
  Xamarin.Forms.Xaml/CreateValuesVisitor.cs
  Xamarin.Forms.Xaml/ExpandMarkupsVisitor.cs
  Xamarin.Forms.Xaml/FillResourceDictionariesVisitor.cs
  Xamarin.Forms.Xaml/NamescopingVisitor.cs
  Xamarin.Forms.Xaml/PruneIgnoredNodesVisitor.cs
  Xamarin.Forms.Xaml/RegisterXNamesVisitor.cs
  Xamarin.Forms.Xaml/XamlNode.cs
  Xamarin.Forms.Xaml/XamlNodeVisitor.cs
Labels: 3.0.0, API-change, i/critical, i/regression

#2516 fix ui test for iOS on Issue2266
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2266.cs
Labels: t/housekeeping

#2468 [Tizen] Supports Switch.OnColor to tizen
  Xamarin.Forms.Platform.Tizen/Renderers/SwitchRenderer.cs
Labels: F100, community-sprint, t/enhancement

#2528 [XamlC] correctly create ldc_i4 for uint
  Xamarin.Forms.Build.Tasks/NodeILExtensions.cs
  Xamarin.Forms.Xaml.UnitTests/Issues/Gh2508.xaml
  Xamarin.Forms.Xaml.UnitTests/Issues/Gh2508.xaml.cs
  Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
Labels: a/Xaml, t/bug

#2523 [XamlC] Import property typeRefs in BindingCompiler
  Xamarin.Forms.Build.Tasks/SetPropertiesVisitor.cs
Labels: a/Xaml, i/critical, t/bug

#2530 [UITests] Bump delay on UITest 32898
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla32898.cs
Labels: t/housekeeping

#2061 [UWP] AccessKey support on VisualElement and TabbedPage
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1672.cs
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
  Xamarin.Forms.Core/PlatformConfiguration/WindowsSpecific/AccessKeyPlacement.cs
  Xamarin.Forms.Core/PlatformConfiguration/WindowsSpecific/VisualElement.cs
  Xamarin.Forms.Platform.UAP/AccessKeyHelper.cs
  Xamarin.Forms.Platform.UAP/TabbedPageRenderer.cs
  Xamarin.Forms.Platform.UAP/VisualElementRenderer.cs
  Xamarin.Forms.Platform.UAP/Xamarin.Forms.Platform.UAP.csproj
Labels: API-change, F100, p/UWP, t/enhancement

#2497 [iOS] Force iOS to end editing when pushing a navigation page
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla33561.cs
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2247.cs
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
  Xamarin.Forms.Controls/TestCases.cs
  Xamarin.Forms.Platform.iOS/Platform.cs
  Xamarin.Forms.Platform.iOS/Renderers/NavigationRenderer.cs
Labels: p/iOS, t/bug

#1984 [iOS] Fixes for RefreshControl with iOS11 LargeTitles
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1905.cs
  Xamarin.Forms.Platform.iOS/Extensions/ViewExtensions.cs
  Xamarin.Forms.Platform.iOS/Renderers/ListViewRenderer.cs
Labels: breaking, p/iOS, t/bug

#2502 [UWP] Fixes the reduced height of the main page
  Xamarin.Forms.Platform.UAP/MasterDetailControl.cs
Labels: p/UWP

#2519 [Core] Improve Renderer registration order
  Xamarin.Forms.ControlGallery.Android/Xamarin.Forms.ControlGallery.Android.csproj
  Xamarin.Forms.ControlGallery.Android/_2489CustomRenderer.cs
  Xamarin.Forms.ControlGallery.WindowsUniversal/Xamarin.Forms.ControlGallery.WindowsUniversal.csproj
  Xamarin.Forms.ControlGallery.WindowsUniversal/_2489CustomRenderer.cs
  Xamarin.Forms.ControlGallery.iOS/Xamarin.Forms.ControlGallery.iOS.csproj
  Xamarin.Forms.ControlGallery.iOS/_2489CustomRenderer.cs
  Xamarin.Forms.Controls/CoreGallery.cs
  Xamarin.Forms.Core/Registrar.cs
  Xamarin.Forms.Platform.Android/Properties/AssemblyInfo.cs
  Xamarin.Forms.Platform.iOS/Properties/AssemblyInfo.cs
Labels: API-change

#2545 Improve warning message, since the calling code isn't on Device
  Xamarin.Forms.Core/Device.cs
Labels: API-change

#1657 [CSS] attribute Source with UriTypeConverter
  Xamarin.Forms.Xaml/MarkupExtensions/StyleSheetExtension.cs
Labels: a/CSS, a/Xaml, a/netstandard, p/UWP, t/bug :bug:

#2544 Fix .css files not excluded from default None items
  .nuspec/Xamarin.Forms.DefaultItems.targets
Labels: a/CSS, a/netstandard, t/housekeeping

#2416 [iOS, UWP] Explicitly dispose of children renderers that belong to Packager
  Xamarin.Forms.ControlGallery.Android/AttachedStateEffectRenderer.cs
  Xamarin.Forms.ControlGallery.Android/Xamarin.Forms.ControlGallery.Android.csproj
  Xamarin.Forms.ControlGallery.WindowsUniversal/AttachedStateEffectRenderer.cs
  Xamarin.Forms.ControlGallery.WindowsUniversal/Xamarin.Forms.ControlGallery.WindowsUniversal.csproj
  Xamarin.Forms.ControlGallery.iOS/AttachedStateEffectRenderer.cs
  Xamarin.Forms.ControlGallery.iOS/Xamarin.Forms.ControlGallery.iOS.csproj
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Effects/AttachedStateEffect.cs
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Effects/AttachedStateEffectList.cs
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2399.cs
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
  Xamarin.Forms.Platform.UAP/ListViewRenderer.cs
  Xamarin.Forms.Platform.UAP/ViewToRendererConverter.cs
  Xamarin.Forms.Platform.UAP/VisualElementPackager.cs
  Xamarin.Forms.Platform.iOS/VisualElementPackager.cs
Labels: p/UWP, p/iOS
