Repository xamarin/Xamarin.Forms, pull requests merged in 2018-03, with the labels that each got.

#1973 [Android] attempt to load images from drawables before using bitmap
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1908.cs
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
  Xamarin.Forms.Platform.Android/Extensions/ImageViewExtensions.cs
Labels: p/Android

#1995 [GTK] Implemented App Lifecycle events
  Xamarin.Forms.Platform.GTK/FormsWindow.cs
Labels: p/gtk, t/enhancement

#1990 [Core] Add Watch to TargetIdiom
  Xamarin.Forms.Core/OnIdiom.cs
  Xamarin.Forms.Core/TargetIdiom.cs
  docs/Xamarin.Forms.Core/Xamarin.Forms/OnIdiom`1.xml
  docs/Xamarin.Forms.Core/Xamarin.Forms/TargetIdiom.xml
Labels: breaking

#1997 [flex] better margin support with Wrap
  Xamarin.Flex/Flex.cs
  Xamarin.Forms.Core.UnitTests/FlexLayoutTests.cs
  Xamarin.Forms.Core/FlexLayout.cs
Labels: a/flex, t/bug

#1976 [Xaml] add DesignMode flag
  Xamarin.Forms.Core/DesignMode.cs
  Xamarin.Forms.Core/Internals/ResourceLoader.cs
  Xamarin.Forms.Platform.UAP/WindowsBasePage.cs
  Xamarin.Forms.Xaml/XamlLoader.cs
  docs/Xamarin.Forms.Core/Xamarin.Forms/DesignMode.xml
  docs/Xamarin.Forms.Core/index.xml
Labels: F100, t/enhancement

#1999 [Android] Verify NavigationPage is attached to hierarchy before pushing pages
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/GitHub1355.cs
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1355.cs
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
  Xamarin.Forms.Platform.Android/AppCompat/NavigationPageRenderer.cs
Labels: i/critical, p/Android

#2010 [Flex] correctly measure images
  Xamarin.Flex/Flex.cs
  Xamarin.Forms.Core/FlexLayout.cs
Labels: a/flex

#2023 [CSS] use `class` instead of `StyleClass`
  Xamarin.Forms.Core/VisualElement.cs
  docs/Xamarin.Forms.Core/Xamarin.Forms/VisualElement.xml
Labels: a/CSS

#1781 [Core,iOS,Android] Color on Slider (Implementation)
  Xamarin.Forms.Core/Slider.cs
  Xamarin.Forms.Platform.Android/Renderers/SliderRenderer.cs
  Xamarin.Forms.Platform.UAP/SliderRenderer.cs
  Xamarin.Forms.Platform.iOS/Renderers/SliderRenderer.cs
  docs/Xamarin.Forms.Core/Xamarin.Forms/Slider.xml
Labels: F100, community-sprint, t/enhancement

#1952 [UWP] Icon on TabbedPage
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1705_2.cs
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
  Xamarin.Forms.Core/PlatformConfiguration/WindowsSpecific/TabbedPage.cs
  Xamarin.Forms.Platform.UAP/TabbedPageRenderer.cs
  Xamarin.Forms.Platform.UAP/TabbedPageStyle.xaml
  docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration.WindowsSpecific/TabbedPage.xml
  docs/Xamarin.Forms.Core/index.xml
Labels: F100, community-sprint, p/UWP, t/enhancement

#2044 Reinstate StyleClass but keep @class
  Xamarin.Forms.Core/VisualElement.cs
  docs/Xamarin.Forms.Core/Xamarin.Forms/VisualElement.xml
Labels: t/housekeeping

#2036 [XamlC] Find the real VisualState parent
  Xamarin.Forms.Build.Tasks/CompiledConverters/BindablePropertyConverter.cs
  Xamarin.Forms.Xaml.UnitTests/Issues/Gh2034.xaml
  Xamarin.Forms.Xaml.UnitTests/Issues/Gh2034.xaml.cs
  Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
Labels: a/VSM, a/Xaml

#1850 [All] Bindable span
  Xamarin.Forms.Controls/CoreGalleryPages/LabelCoreGalleryPage.cs
  Xamarin.Forms.Controls/GalleryPages/LabelGallery.cs
  Xamarin.Forms.Core.UnitTests/SpanTests.cs
  Xamarin.Forms.Core.UnitTests/Xamarin.Forms.Core.UnitTests.csproj
  Xamarin.Forms.Core/BindableProperty.cs
  Xamarin.Forms.Core/FormattedString.cs
  Xamarin.Forms.Core/Label.cs
  Xamarin.Forms.Core/MergedStyle.cs
  Xamarin.Forms.Core/Span.cs
  Xamarin.Forms.Core/VisualElement.cs
  Xamarin.Forms.Platform.Android/Renderers/FormattedStringExtensions.cs
  Xamarin.Forms.Platform.GTK/Extensions/LabelExtensions.cs
  Xamarin.Forms.Platform.Tizen/Cells/CellRenderer.cs
  Xamarin.Forms.Platform.Tizen/Cells/TextCellRenderer.cs
  Xamarin.Forms.Platform.Tizen/Renderers/LabelRenderer.cs
  Xamarin.Forms.Platform.UAP/LabelRenderer.cs
  Xamarin.Forms.Platform.WPF/Extensions/FormattedStringExtensions.cs
  Xamarin.Forms.Platform.iOS/Renderers/FormattedStringExtensions.cs
  docs/Xamarin.Forms.Core/Xamarin.Forms/FormattedString.xml
  docs/Xamarin.Forms.Core/Xamarin.Forms/Label.xml
  docs/Xamarin.Forms.Core/Xamarin.Forms/Span.xml
Labels: DO-NOT-MERGE-!!! :stop_sign:, F100, community-sprint, t/enhancement

#2055 [C] do not return IsSet for BP with defaultVC
  Xamarin.Forms.Core.UnitTests/BindableObjectUnitTests.cs
  Xamarin.Forms.Core/BindableObject.cs
Labels: a/binding, t/bug

#2053 [C] Update Bindings with "BindingContext" in path
  Xamarin.Forms.Core.UnitTests/BindableObjectUnitTests.cs
  Xamarin.Forms.Core/BindingExpression.cs
Labels: a/binding

#2089 [Xaml] better error reporting on x:Reference
  Xamarin.Forms.Xaml.UnitTests/Issues/Gh2007.xaml
  Xamarin.Forms.Xaml.UnitTests/Issues/Gh2007.xaml.cs
  Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
  Xamarin.Forms.Xaml/MarkupExtensions/ReferenceExtension.cs
Labels: a/Xaml, t/enhancement

#2076 [XamlC] report undeclared xmlns on custom markups
  Xamarin.Forms.Build.Tasks/ExpandMarkupsVisitor.cs
  Xamarin.Forms.Build.Tasks/XmlTypeExtensions.cs
  Xamarin.Forms.Xaml.UnitTests/Issues/Gh2034.xaml.cs
  Xamarin.Forms.Xaml.UnitTests/Issues/Gh2063.xaml
  Xamarin.Forms.Xaml.UnitTests/Issues/Gh2063.xaml.cs
  Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
Labels: a/Xaml, t/enhancement

#2078 [XamlC] report missing ctor param
  Xamarin.Forms.Build.Tasks/CreateObjectVisitor.cs
  Xamarin.Forms.Xaml.UnitTests/Issues/Gh2064.xaml
  Xamarin.Forms.Xaml.UnitTests/Issues/Gh2064.xaml.cs
  Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
Labels: a/Xaml, t/enhancement

#2083 Fix VS errors when loading clean solution; prevent VS rewriting Android project files
  EmbeddingTestBeds/Embedding.Droid/Embedding.Droid.csproj
  EmbeddingTestBeds/Embedding.XF/Embedding.XF.csproj
  PagesGallery/PagesGallery.Droid/PagesGallery.Droid.csproj
  PagesGallery/PagesGallery.UWP/PagesGallery.UWP.csproj
  PagesGallery/PagesGallery.iOS/PagesGallery.iOS.csproj
  PagesGallery/PagesGallery/PagesGallery.csproj
  Stubs/Xamarin.Forms.Platform.Android/Xamarin.Forms.Platform.Android (Forwarders).csproj
  Xamarin.Forms.ControlGallery.Android/Xamarin.Forms.ControlGallery.Android.csproj
  Xamarin.Forms.Controls/Xamarin.Forms.Controls.csproj
  Xamarin.Forms.Maps.Android/Xamarin.Forms.Maps.Android.csproj
  Xamarin.Forms.Platform.Android.AppLinks/Xamarin.Forms.Platform.Android.AppLinks.csproj
  Xamarin.Forms.Platform.Android.FormsViewGroup/Xamarin.Forms.Platform.Android.FormsViewGroup.csproj
  Xamarin.Forms.Platform.Android/Xamarin.Forms.Platform.Android.csproj
  Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
Labels: t/housekeeping

#2065 [UWP] Thumb color and image for Slider
  .nuspec/Xamarin.Forms.nuspec
  Xamarin.Forms.Controls/CoreGalleryPages/SliderCoreGalleryPage.cs
  Xamarin.Forms.CustomAttributes/TestAttributes.cs
  Xamarin.Forms.Platform.UAP/FormsSlider.cs
  Xamarin.Forms.Platform.UAP/Resources.xaml
  Xamarin.Forms.Platform.UAP/SliderRenderer.cs
  Xamarin.Forms.Platform.UAP/SliderStyle.xaml
  Xamarin.Forms.Platform.UAP/Xamarin.Forms.Platform.UAP.csproj
Labels: F100, t/enhancement

#2091 Editor Auto Resize with Text Changes
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1733.cs
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
  Xamarin.Forms.Core/Editor.cs
  Xamarin.Forms.Core/EditorAutoSizeOption.cs
  Xamarin.Forms.Platform.UAP/EditorRenderer.cs
  Xamarin.Forms.Platform.iOS/Renderers/EditorRenderer.cs
  docs/Xamarin.Forms.Core/Xamarin.Forms/Editor.xml
  docs/Xamarin.Forms.Core/Xamarin.Forms/EditorAutoSizeOption.xml
  docs/Xamarin.Forms.Core/index.xml
Labels: F100, t/enhancement

#2101 [UWP] MDP should respect HasNavigationBar for current page
  Xamarin.Forms.Platform.UAP/MasterDetailControl.cs
  Xamarin.Forms.Platform.UAP/MasterDetailPageRenderer.cs
Labels: p/UWP

#2066 [Android] Fix issue where compressed layouts couldn't be removed from the visual hierarchy
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1601.cs
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
  Xamarin.Forms.Platform.Android/VisualElementPackager.cs
Labels: i/critical, p/Android

#2029 [Enhancement] Entry ReturnType
  Xamarin.Forms.Controls/ControlGalleryPages/EntryReturnTypeGalleryPage.cs
  Xamarin.Forms.Controls/CoreGallery.cs
  Xamarin.Forms.Core.UnitTests/EntryUnitTests.cs
  Xamarin.Forms.Core/Entry.cs
  Xamarin.Forms.Core/ReturnType.cs
  Xamarin.Forms.Platform.Android/Extensions/EntryRendererExtensions.cs
  Xamarin.Forms.Platform.Android/Renderers/EntryRenderer.cs
  Xamarin.Forms.Platform.Tizen/Extensions/EntryExtensions.cs
  Xamarin.Forms.Platform.Tizen/Renderers/EntryRenderer.cs
  Xamarin.Forms.Platform.UAP/EntryRenderer.cs
  Xamarin.Forms.Platform.UAP/Extensions.cs
  Xamarin.Forms.Platform.iOS/Extensions/Extensions.cs
  Xamarin.Forms.Platform.iOS/Renderers/EntryRenderer.cs
  docs/Xamarin.Forms.Core/Xamarin.Forms/Entry.xml
  docs/Xamarin.Forms.Core/Xamarin.Forms/ReturnType.xml
  docs/Xamarin.Forms.Core/index.xml
Labels: F100, t/enhancement

#2108 [Nuget] Update nuspec's with msft info
  .nuspec/Xamarin.Forms.AppLinks.nuspec
  .nuspec/Xamarin.Forms.Maps.GTK.nuspec
  .nuspec/Xamarin.Forms.Maps.WPF.nuspec
  .nuspec/Xamarin.Forms.Maps.nuspec
  .nuspec/Xamarin.Forms.Pages.Azure.nuspec
  .nuspec/Xamarin.Forms.Pages.nuspec
  .nuspec/Xamarin.Forms.Platform.GTK.nuspec
  .nuspec/Xamarin.Forms.Platform.WPF.nuspec
  .nuspec/Xamarin.Forms.nuspec
Labels: t/housekeeping

#2038 Added the Entry.IsTextPredictionEnabled property
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1677.cs
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
  Xamarin.Forms.Core/Entry.cs
  Xamarin.Forms.Platform.Android/Renderers/EntryRenderer.cs
  Xamarin.Forms.Platform.UAP/EntryRenderer.cs
  Xamarin.Forms.Platform.iOS/Renderers/EntryRenderer.cs
  docs/Xamarin.Forms.Core/Xamarin.Forms/Entry.xml
Labels: F100, t/enhancement

#2109 [iOS] Set UITabBarItem colours when they are added
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1323.cs
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
  Xamarin.Forms.Platform.iOS/Renderers/TabbedRenderer.cs
Labels: p/iOS

#2095 [iOS] Use UINavigationBar.Appearance.LargeTitleTextAttributes if specified
  Xamarin.Forms.ControlGallery.iOS/AppDelegate.cs
  Xamarin.Forms.Platform.iOS/Renderers/NavigationRenderer.cs
Labels: p/iOS

#2111 [iOS] Encode url for UIWebView so it doesn't fail with non-ascii characters
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1583_1.cs
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
  Xamarin.Forms.Platform.iOS/Renderers/WebViewRenderer.cs
Labels: p/iOS

#2114 [Android] Button PaddingLeft now accounts for ShadowDx
  Xamarin.Forms.Platform.Android/Renderers/ButtonDrawable.cs
Labels: i/regression, p/Android

#2133 [iOS] Allow user interaction with blurred elements
  Xamarin.Forms.Controls/GalleryPages/PlatformSpecificsGalleries/VisualElementiOS.cs
  Xamarin.Forms.Platform.iOS/VisualElementRenderer.cs
Labels: p/iOS, t/bug

#2147 [Tizen] Change the appearance of Entry/Editor even better
  Xamarin.Forms.Platform.Tizen/Native/EditfieldEntry.cs
  Xamarin.Forms.Platform.Tizen/Renderers/EditorRenderer.cs
  Xamarin.Forms.Platform.Tizen/Renderers/EntryRenderer.cs
Labels: t/enhancement

#2131 [C] avoid exception on overriden indexer
  Xamarin.Forms.Core/BindingExpression.cs
Labels: i/critical, t/bug

#1929 [Core,iOS,Android] Color on Switch
  Xamarin.Forms.Core/Switch.cs
  Xamarin.Forms.Platform.Android/AppCompat/SwitchRenderer.cs
  Xamarin.Forms.Platform.Android/Renderers/SwitchRenderer.cs
  Xamarin.Forms.Platform.iOS/Renderers/SwitchRenderer.cs
  docs/Xamarin.Forms.Core/Xamarin.Forms/Switch.xml
Labels: F100, community-sprint, t/enhancement

#2156 [MacOS] Implement the navigation events on MacOS
  Xamarin.Forms.Platform.MacOS/Renderers/WebViewRenderer.cs
Labels: p/macOS

#2031 Add UI Test for B60699
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla60699.cs
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Labels: t/housekeeping

#2140 [Enhancement] Add EvaluateJavaScript method to WebView
  Xamarin.Forms.Controls/CoreGalleryPages/WebViewCoreGalleryPage.cs
  Xamarin.Forms.Core/IWebViewController.cs
  Xamarin.Forms.Core/Internals/EvalRequested.cs
  Xamarin.Forms.Core/WebView.cs
  Xamarin.Forms.CustomAttributes/TestAttributes.cs
  Xamarin.Forms.Platform.Android/Renderers/WebViewRenderer.cs
  Xamarin.Forms.Platform.GTK/Renderers/WebViewRenderer.cs
  Xamarin.Forms.Platform.MacOS/Renderers/WebViewRenderer.cs
  Xamarin.Forms.Platform.Tizen/Renderers/WebViewRenderer.cs
  Xamarin.Forms.Platform.UAP/WebViewRenderer.cs
  Xamarin.Forms.Platform.WPF/Renderers/WebViewRenderer.cs
  Xamarin.Forms.Platform.iOS/Renderers/WebViewRenderer.cs
  docs/Xamarin.Forms.Core/Xamarin.Forms.Internals/EvaluateJavaScriptDelegate.xml
  docs/Xamarin.Forms.Core/Xamarin.Forms/IWebViewController.xml
  docs/Xamarin.Forms.Core/Xamarin.Forms/WebView.xml
  docs/Xamarin.Forms.Core/index.xml
Labels: API-change, F100, t/enhancement

#2158 [Core] Fix CommonStates.Focused issue
  Xamarin.Forms.Core/VisualElement.cs
Labels: t/bug

#2166 [WPF] Fix bug : Xamarin.Forms WPF load local html throw ArgumentException with message "Relative URIs are not allowed"
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1864.cs
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
  Xamarin.Forms.CustomAttributes/TestAttributes.cs
  Xamarin.Forms.Platform.WPF/Renderers/WebViewRenderer.cs
Labels: i/critical, p/WPF, t/bug

#2185 [Xaml[C]] properly parse nested markups
  Xamarin.Forms.Xaml.UnitTests/Issues/Gh2171.xaml
  Xamarin.Forms.Xaml.UnitTests/Issues/Gh2171.xaml.cs
  Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
  Xamarin.Forms.Xaml/MarkupExpressionParser.cs
Labels: a/Xaml, t/bug

#2186 [C] move ListView code out of ItemsView
  Xamarin.Forms.Core/ItemsView.cs
  Xamarin.Forms.Core/ListView.cs
Labels: API-change

#2143 Added the ListView.SelectionMode property
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla59718.cs
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1801.cs
  Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
  Xamarin.Forms.Core/ListView.cs
  Xamarin.Forms.Core/ListViewSelectionMode.cs
  Xamarin.Forms.Platform.Android/Renderers/ListViewAdapter.cs
  Xamarin.Forms.Platform.Android/Renderers/ListViewRenderer.cs
  Xamarin.Forms.Platform.UAP/ListViewRenderer.cs
  Xamarin.Forms.Platform.UAP/TableViewRenderer.cs
  Xamarin.Forms.Platform.iOS/Renderers/ListViewRenderer.cs
Labels: API-change, F100, t/enhancement
