Repository xamarin/Xamarin.Forms, pull requests merged in 2022-02, with the labels that each got.

#13528 #13527 - OnAppearing() is now called on every back navigation again b…
  Xamarin.Forms.Platform.UAP/Platform.cs
Labels: t/bug :bug:, p/UWP, a/modal, a/lifecycleevents, a/navigation, a/page

#15124 removed a broken direct link to net47 dev pack
  build.cake
Labels: t/housekeeping ♻︎

#15117 Fix NRE in iOS ImageRenderer
  Xamarin.Forms.Platform.iOS/Renderers/ImageRenderer.cs
Labels: p/iOS 🍎, a/image
